name: my_portfolio
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.2.19
  scroll_to_index: ^3.0.1
  carousel_slider: ^4.2.1
  mailto: ^2.0.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# ON CHANGE: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/ZC_Logo.png"
    background_color: "#010208"
    theme_color: "#010208"

# ON CHANGE: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#010208"
  image: "assets/images/ZC_Logo.png"

flutter:
  uses-material-design: true
