name: my_portfolio
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  scrollable_positioned_list: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/ZC_Logo_white.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
